### ISSUE TITLE
Docker 

### ISSUE THREAD

**Issue by armdan** [michaelx/media-tracker#11]
Any plans to dockerize this great project?

**Comment by michaelx** [comment]
Yes, but not sure when exactly I‘ll find time to do it though. Happy to accept a PR with `nginx` though.

**Comment by bloomvdomino** [comment]
Dockerizing would require to build two separate images, for the client and the server. Otherwise the container must run something like `supervisord`, and that isn't the best idea and style.

Maybe I'll write a `Dockerfile` draft and post it here…

**Comment by MilorES** [comment]
nothing posted? Did this nice project die?

**Comment by michaelx** [comment]
> nothing posted? Did this nice project die?

I still like the product & idea, but unfortunately can’t prioritize it at the moment.

**Comment by MilorES** [comment]
Thank you for your answer, unfortunately my level is not enough to contribute with code. Can I invite you to a coffee? "That is to say, donate something symbolic" (I have not been able to see it).
