### ISSUE TITLE
How to add the API key to config.js

### ISSUE THREAD

**Issue by superbonaci** [michaelx/media-tracker#42]
How to I add the TMDb API key to `./client/src/config.js`?

**Comment by superbonaci** [comment]
Fixed. Go to your account page: https://www.themoviedb.org/settings/api
Then copy the `API Key (v3 auth)`, which is 32 characters long, (the v4 doesn't work) and make `./client/src/config.js` look like this:
```
export default {
  TMDb: {
    KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    LANGUAGE: 'en-us',
  },
};
```

**Comment by librafrog** [comment]
@michaelx sorry to bother you but, currently I'm getting an error when starting the client. The pattern is same as above. Maybe a way to tell npm to ignore the warnings
<details>
<summary>frontend side</summary>
<pre>
Starting the development server...
Compiled with warnings.

[eslint]
src\config.js
  Line 1:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src\reducers\allTodosReducer.js
  Line 6:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src\reducers\doneTodosReducer.js
  Line 6:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src\reducers\mediaDetailsReducer.js
  Line 1:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src\reducers\mediaEpisodesReducer.js
  Line 1:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src\reducers\relatedMediaReducer.js
  Line 1:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src\reducers\searchReducer.js
  Line 7:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src\reducers\todoReducer.js
  Line 1:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src\reducers\trendingReducer.js
  Line 6:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src\reducers\uiReducer.js
  Line 7:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint]
src\config.js
  Line 1:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src\reducers\allTodosReducer.js
  Line 6:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src\reducers\doneTodosReducer.js
  Line 6:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export
</details>

**Comment by superbonaci** [comment]
@librafrog why don't you open a new issue? Yours doesn't seem related to mine.
