### ISSUE TITLE
Disable automatic launching of web browser when starting client

### ISSUE THREAD

**Issue by superbonaci** [michaelx/media-tracker#46]
Each time I run `npm start` on client folder, it launches my default web browser. Request patch to be able to configure this.

**Comment by superbonaci** [comment]
Comment the line `media-tracker/client/node_modules/react-dev-utils/openBrowser.js:108` with `//` in front of the line:
````
// open(url, options).catch(() => {}); // Prevent `unhandledRejection` error.
````

**Comment by michaelx** [comment]
There is a browser env that can be used to achieve this. See https://create-react-app.dev/docs/advanced-configuration/. That way you don’t have to touch any packages.
